auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /home/jeff/claude-code/agent-telemetry/loki-data
  storage:
    filesystem:
      chunks_directory: /home/jeff/claude-code/agent-telemetry/loki-data/chunks
      rules_directory: /home/jeff/claude-code/agent-telemetry/loki-data/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

# Accept logs via HTTP API
ingester:
  max_chunk_age: 1h
  chunk_retain_period: 30s
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s

# Configure limits for telemetry ingestion
limits_config:
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  per_stream_rate_limit: 5MB
  per_stream_rate_limit_burst: 10MB
  max_streams_per_user: 0
  max_line_size: 256KB
  retention_period: 30d

# Enable API endpoints for log ingestion
distributor:
  ring:
    kvstore:
      store: inmemory

# Table manager for retention
table_manager:
  retention_deletes_enabled: true
  retention_period: 30d

# Frontend for queries
frontend:
  max_outstanding_per_tenant: 100
  compress_responses: true

# Compactor for log retention
compactor:
  working_directory: /home/jeff/claude-code/agent-telemetry/loki-data/compactor
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  delete_request_store: filesystem